// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package gRPC

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TodosRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodosRequest) Reset()         { *m = TodosRequest{} }
func (m *TodosRequest) String() string { return proto.CompactTextString(m) }
func (*TodosRequest) ProtoMessage()    {}
func (*TodosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *TodosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodosRequest.Unmarshal(m, b)
}
func (m *TodosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodosRequest.Marshal(b, m, deterministic)
}
func (m *TodosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodosRequest.Merge(m, src)
}
func (m *TodosRequest) XXX_Size() int {
	return xxx_messageInfo_TodosRequest.Size(m)
}
func (m *TodosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TodosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TodosRequest proto.InternalMessageInfo

type TodosReply struct {
	Todo                 []*TodoReply `protobuf:"bytes,1,rep,name=Todo,proto3" json:"Todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TodosReply) Reset()         { *m = TodosReply{} }
func (m *TodosReply) String() string { return proto.CompactTextString(m) }
func (*TodosReply) ProtoMessage()    {}
func (*TodosReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *TodosReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodosReply.Unmarshal(m, b)
}
func (m *TodosReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodosReply.Marshal(b, m, deterministic)
}
func (m *TodosReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodosReply.Merge(m, src)
}
func (m *TodosReply) XXX_Size() int {
	return xxx_messageInfo_TodosReply.Size(m)
}
func (m *TodosReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TodosReply.DiscardUnknown(m)
}

var xxx_messageInfo_TodosReply proto.InternalMessageInfo

func (m *TodosReply) GetTodo() []*TodoReply {
	if m != nil {
		return m.Todo
	}
	return nil
}

type TodoReply struct {
	ID                   int64                `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Content              string               `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	Done                 bool                 `protobuf:"varint,3,opt,name=Done,proto3" json:"Done,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TodoReply) Reset()         { *m = TodoReply{} }
func (m *TodoReply) String() string { return proto.CompactTextString(m) }
func (*TodoReply) ProtoMessage()    {}
func (*TodoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{2}
}

func (m *TodoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoReply.Unmarshal(m, b)
}
func (m *TodoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoReply.Marshal(b, m, deterministic)
}
func (m *TodoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoReply.Merge(m, src)
}
func (m *TodoReply) XXX_Size() int {
	return xxx_messageInfo_TodoReply.Size(m)
}
func (m *TodoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoReply.DiscardUnknown(m)
}

var xxx_messageInfo_TodoReply proto.InternalMessageInfo

func (m *TodoReply) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TodoReply) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *TodoReply) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *TodoReply) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *TodoReply) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *TodoReply) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*TodosRequest)(nil), "gRPC.TodosRequest")
	proto.RegisterType((*TodosReply)(nil), "gRPC.TodosReply")
	proto.RegisterType((*TodoReply)(nil), "gRPC.TodoReply")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xdd, 0x26, 0x56, 0x33, 0x95, 0x2a, 0x73, 0x5a, 0x72, 0x31, 0xc4, 0x4b, 0x2e, 0x6e,
	0x31, 0x22, 0x78, 0x95, 0x04, 0xa4, 0x37, 0x59, 0xea, 0x0f, 0x68, 0xc9, 0x18, 0x84, 0x34, 0x13,
	0x9b, 0xe9, 0xa1, 0xbf, 0xdc, 0xab, 0x64, 0xd3, 0xa4, 0x78, 0xea, 0x6d, 0xdf, 0xdb, 0xf7, 0x0d,
	0xbc, 0x07, 0x20, 0x5c, 0xb0, 0x69, 0x76, 0x2c, 0x8c, 0x7e, 0x69, 0x3f, 0xb2, 0xf0, 0xbe, 0x64,
	0x2e, 0x2b, 0x5a, 0x38, 0x6f, 0xb3, 0xff, 0x5a, 0xc8, 0xf7, 0x96, 0x5a, 0x59, 0x6f, 0x9b, 0x3e,
	0x16, 0xcf, 0xe1, 0x66, 0xc5, 0x05, 0xb7, 0x96, 0x7e, 0xf6, 0xd4, 0x4a, 0xfc, 0x04, 0x70, 0xd4,
	0x4d, 0x75, 0xc0, 0x07, 0xf0, 0x3b, 0xa5, 0x55, 0xe4, 0x25, 0xb3, 0xf4, 0xd6, 0x74, 0x37, 0x4d,
	0xe7, 0xb8, 0x6f, 0xeb, 0x3e, 0xe3, 0x5f, 0x05, 0xc1, 0xe8, 0xe1, 0x1c, 0x26, 0xcb, 0x5c, 0xab,
	0x48, 0x25, 0x9e, 0x9d, 0x2c, 0x73, 0xd4, 0x70, 0x95, 0x71, 0x2d, 0x54, 0x8b, 0x9e, 0x44, 0x2a,
	0x09, 0xec, 0x20, 0x11, 0xc1, 0xcf, 0xb9, 0x26, 0xed, 0x45, 0x2a, 0xb9, 0xb6, 0xee, 0x8d, 0xaf,
	0x10, 0x64, 0x3b, 0x5a, 0x0b, 0x15, 0x6f, 0xa2, 0xfd, 0x48, 0x25, 0xb3, 0x34, 0x34, 0x7d, 0x07,
	0x33, 0x74, 0x30, 0xab, 0xa1, 0x83, 0x3d, 0x85, 0x3b, 0xf2, 0xb3, 0x29, 0x8e, 0xe4, 0xe5, 0x79,
	0x72, 0x0c, 0x77, 0x64, 0x4e, 0x15, 0xf5, 0xe4, 0xf4, 0x3c, 0x39, 0x86, 0xd3, 0x97, 0x7e, 0x1e,
	0x7c, 0x04, 0xef, 0x9d, 0x04, 0xf1, 0xb4, 0xcf, 0xb0, 0x67, 0x78, 0xf7, 0xcf, 0x6b, 0xaa, 0x43,
	0x7c, 0xb1, 0x99, 0xba, 0xab, 0xcf, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xc7, 0x76, 0xa1,
	0xaf, 0x01, 0x00, 0x00,
}
